CREATE TABLE Age_Levels
(	
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Age_Levels_PK PRIMARY KEY(ID),
	CONSTRAINT Age_Levels_NAME UNIQUE(NAME)
);

CREATE TABLE Sections
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Sections_PK PRIMARY KEY(ID),
	CONSTRAINT Sections_NAME UNIQUE(NAME)
);

CREATE TABLE Publishers
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Publishers_PK PRIMARY KEY(ID),
	CONSTRAINT Publishers_NAME UNIQUE(NAME)
);

CREATE TABLE Languages
( 
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Languages_PK PRIMARY KEY(ID),
	CONSTRAINT Languages_NAME UNIQUE(NAME)

);

CREATE TABLE Authors_Name
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Authors_Name_PK PRIMARY KEY(ID),
	CONSTRAINT Authors_Name_NAME UNIQUE(NAME)
);

CREATE TABLE Roles
( 
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Roles_PK PRIMARY KEY(ID),
	CONSTRAINT Roles_NAME UNIQUE(NAME)

);

CREATE TABLE Cities
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Cities_PK PRIMARY KEY(ID),
	CONSTRAINT Cities_NAME UNIQUE(NAME)
);

CREATE TABLE Genre_Names
(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT Genre_Names_PK PRIMARY KEY(ID),
	CONSTRAINT Genr_Names_NAME UNIQUE(NAME)
);

CREATE TABLE Address
(	ID INT NOT NULL,
	Street VARCHAR(30) NOT NULL,
	ID_Cities INT NOT NULL,
	CONSTRAINT Adress_PK PRIMARY KEY(ID),
	CONSTRAINT Adress_Cities_FK FOREIGN KEY (ID_Cities) REFERENCES Cities(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Customers
(
	 ID INT NOT NULL,
	 NAME VARCHAR(50) NOT NULL,
	 ID_Address INT,
	 No_of_penalties INT,
	 Description VARCHAR(1000), 
	 CONSTRAINT Customers_PK PRIMARY KEY(ID),
	 CONSTRAINT Customers_ID_Address_FK FOREIGN KEY (ID_Address) REFERENCES Address(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Books
(
	 ID INT NOT NULL,
	 NAME VARCHAR(50) NOT NULL,
	 No_of_pages INT,
	 Cover VARCHAR(200),
	 Year_of_release INT,
	 Description VARCHAR(2000),
	 ID_Age_Levels INT,
	 ID_Sections INT,
	 ID_Original_Language_1 INT,
	 ID_Original_Language_2 INT,
	 CONSTRAINT Books_PK PRIMARY KEY(ID),
	 CONSTRAINT Books_ID_Age_Levels_FK FOREIGN KEY (ID_Age_Levels) REFERENCES Age_Levels(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	 CONSTRAINT Books_ID_Sections_FK FOREIGN KEY (ID_Sections) REFERENCES Sections(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	 CONSTRAINT Books_ID_Original_Language_1_FK FOREIGN KEY (ID_Original_Language_1) REFERENCES Languages(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	 CONSTRAINT Books_ID_Original_Language_2_FK FOREIGN KEY (ID_Original_Language_2) REFERENCES Languages(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Genres
(	ID INT NOT NULL,
	ID_Books INT NOT NULL,
	ID_Genre_Names INT NOT NULL,
	CONSTRAINT Genres_PK PRIMARY KEY(ID),
	CONSTRAINT Genres_Books_FK FOREIGN KEY (ID_Books) REFERENCES Books(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Genres_Genre_Names_FK FOREIGN KEY (ID_Genre_Names) REFERENCES Genre_Names(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Ratings
(	ID INT NOT NULL,
	Name VARCHAR(50),
	ID_Customer INT,
	Stars INT NOT NULL,
	Review VARCHAR(8000),
	Date_of_review DATE NOT NULL,
	ID_Books INT NOT NULL,
	CONSTRAINT Ratings_PK PRIMARY KEY(ID),
	CONSTRAINT Ratings_Customer_FK FOREIGN KEY (ID_Customer) REFERENCES Customers(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Ratings_Books_FK FOREIGN KEY (ID_Books) REFERENCES Books(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Copies
(
	 ID INT NOT NULL,
	 ID_Books INT NOT NULL,
	 Serial_Number INT NOT NULL UNIQUE,
	 Type_of_cover VARCHAR(30),
	 No_of_pages INT,
	 State_of_copy VARCHAR(100),
	 ID_Publisher INT,
	 ID_Language_1 INT,
	 ID_Language_2 INT,
	 CONSTRAINT Copies_PK PRIMARY KEY(ID),
	 CONSTRAINT Copies_ID_Books_FK FOREIGN KEY (ID_Books) REFERENCES Books(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	 CONSTRAINT Copies_ID_Publisher_FK FOREIGN KEY (ID_Publisher) REFERENCES Publishers(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	 CONSTRAINT Copies_ID_Language_1_FK FOREIGN KEY (ID_Language_1) REFERENCES Languages(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	 CONSTRAINT Copies_ID_Language_2_FK FOREIGN KEY (ID_Language_2) REFERENCES Languages(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Renting
(	ID INT NOT NULL,
	ID_Customer INT NOT NULL,
	ID_Copies INT NOT NULL UNIQUE,
	Date_of_borrowing DATE NOT NULL,
	When_to_return DATE NOT NULL,
	Date_of_Return DATE,
	Notes VARCHAR(500),
	CONSTRAINT Renting_PK PRIMARY KEY(ID),
	CONSTRAINT Renting_ID_Customer_FK FOREIGN KEY (ID_Customer) REFERENCES Customers(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Renting_ID_Copies_FK FOREIGN KEY (ID_Copies) REFERENCES Copies(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Authors
(	ID INT NOT NULL,
	ID_Authors_Name INT,
	ID_Role INT,
	ID_Books INT NOT NULL,
	Description VARCHAR(800),
	CONSTRAINT Authors_PK PRIMARY KEY(ID),
	CONSTRAINT Authors_ID_Authors_Name_FK FOREIGN KEY (ID_Authors_Name) REFERENCES Authors_Name(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Authors_ID_Role_FK FOREIGN KEY (ID_Role) REFERENCES Roles(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT Authors_Books_FK FOREIGN KEY (ID_Books) REFERENCES Books(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

